// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DecryptText(arg1:string,arg2:string):Promise<main.EncryptionResult>;

export function EncryptText(arg1:string,arg2:string):Promise<main.EncryptionResult>;

export function GenerateRandomKey(arg1:number):Promise<string>;

export function GetDefaultKey():Promise<string>;

export function GetSystemTheme():Promise<string>;
