// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DecryptText(arg1, arg2) {
  return window['go']['main']['App']['DecryptText'](arg1, arg2);
}

export function EncryptText(arg1, arg2) {
  return window['go']['main']['App']['EncryptText'](arg1, arg2);
}

export function GenerateRandomKey(arg1) {
  return window['go']['main']['App']['GenerateRandomKey'](arg1);
}

export function GetDefaultKey() {
  return window['go']['main']['App']['GetDefaultKey']();
}

export function GetSystemTheme() {
  return window['go']['main']['App']['GetSystemTheme']();
}
